spring:
   application:
      name: greeteing-service
management:
   endpoints:
      web:
          exposure:
             include: 
                - '*'
greeting-service:
   greeting: "Hello"
   default-value: "World"